### ISSUE TITLE
Make pyproject.toml wrapper generate section a dict

### ISSUE THREAD

**Issue by auscompgeek** [robotpy/robotpy-build#131]
Instead of:

```toml
[tool.robotpy-build.wrappers.foo]
generate = [
  { Foo = "foo/Foo.h" },
  { Bar = "foo/Bar.h" },
]
```

make it look like this:

```toml
[tool.robotpy-build.wrappers.foo.generate]
Foo = "foo/Foo.h"
Bar = "foo/Bar.h"
```

so that it's a bit less unwieldy.
