### ISSUE TITLE
Add mechanism to inject new methods directly

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-build#72]
Instead of using the inline_cpp block. 

In particular, this would be useful for `__repr__` methods. Not sure how this would work out..

```
extra_methods:
  __repr__:
    cpp_code: |
       [](Type * self) { return "<Type>"; }
```
